#
# Blog Settings
#
author: Christopher & Erica Tobin
title: The Bear and the Frog
subtitle: 
description: 
url: https://703group.github.io/
baseurl: /The-Bear-and-the-Frog

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
